### ISSUE TITLE
Terminating bluelet running server

### ISSUE THREAD

**Issue by teknogeek** [sampsyo/bluelet#8]
Is there any way to exit a running `bluelet.run(bluelet.server(host, port, handler_coro))`? I have a bunch in separate threads and I need a way to get them to exit with the main thread

**Comment by sampsyo** [comment]
Good question. Have you tried kill_thread? https://github.com/sampsyo/bluelet/blob/master/bluelet.py#L281

**Comment by teknogeek** [comment]
As bad and messy as this is, the best way I've found to do this (since posting this) is to `os._exit(0)` because I am trying to exit the bluelet server from outside of the threads and it would be more work than it's worth to try and implement it into my coro.

**Comment by sampsyo** [comment]
Ah, I see. There's still a chance you could construct that KillEvent from outside of a thread and it would still work...

**Comment by teknogeek** [comment]
Okay, maybe i will try that later. thanks!

**Comment by teknogeek** [comment]
Just as a quick update, implementing the `bluelet.kill` was actually much easier than I was presuming it would be earlier and I have done so now.

In my `__init__()`:
```python
def __init__(self):
    ....
    self.server = bluelet.server(host, port, coro)
    ...
    bluelet.run(self.server)

def coro(self, conn):
    try:
        while True:
            data = yield conn.recv(1024)
            
            if not data:
                break
                
            if data == "exit":
                yield bluelet.kill(self.server)
            ...
    except socket.error:
        pass

**Comment by teknogeek** [comment]
thanks for all your help @sampsyo!

**Comment by sampsyo** [comment]
Yay! :tada:
